In [201]:
import numpy as np

# 수학적인 연산을 위한 것
# 배열과 관련된 것들을 쉽고 빠르게 계산 가능
# 함수를 외워서 사용하는 것이라고 생각하면 될 것

In [202]:
# numpy 배열은 일반 array 가 아닌, ndarray 라고 한다.
# 특징은 숫자 데이터만 들어간다는 것, 텍스트 데이터는 들어갈 수 없다.

arr1 = np.array([1, 2, 3])

# 1차원 배열 벡터
print(type(arr1))

<class 'numpy.ndarray'>


In [203]:
arr2 = np.array([[1,2,3],
                [4,5,6]])

print(arr2)
# 2차원 배열 메트릭스
# 3차원부터 텐서 라고 한다.

# ndarray 는 실제로 잘 사용되진 않는다.

[[1 2 3]
 [4 5 6]]


In [204]:
# np.arange

arr = np.arange(10)
arr

# numpy 와 list 의 차이를 잘 알아둘 것.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
arr = np.arange(1,10, 2)
arr

array([1, 3, 5, 7, 9])

# **다차원** 배열 만들기
*   np.zeros
*   np.ones
*   np.full






In [207]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [208]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [209]:
np.zeros((3,4,5))
# 3차원 배열

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [210]:
np.zeros((3,4,5,6)).shape

# 보통 3차원 이상부터는 이렇게 확인만 한다

(3, 4, 5, 6)

In [211]:
np.zeros((3,4,5)).ndim
#차원 수 확인하기

3

In [212]:
np.ones(5)

# 데이터를 1로 채워준다

array([1., 1., 1., 1., 1.])

In [213]:
np.ones((2,3))

# 1로 채워진 2차원 배열

array([[1., 1., 1.],
       [1., 1., 1.]])

In [214]:
np.ones((2, 3)) * 5

# 5로 채워진 2차원 배열을 만드는 방법

array([[5., 5., 5.],
       [5., 5., 5.]])

In [215]:
np.full((3, 4), 7)

# 3행 4열의 행렬을 7로 채우겠다. 
# 위에 있는 방법과 다른 방법 but 같은 결과

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## 단위행렬 만들기 
# np.eye

In [216]:
np.eye(3)

# 주로 선형대수에서 많이 사용한다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [217]:
np.eye(3,4)

# 가능하지만, 잘 사용되지 않는다.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 구간 나누기 np.linspace

In [218]:
np.linspace(1, 10, 3)

# 1부터 10까지 3등분
# 균등한 x축을 만들때 필요
# 시각화 할때 필요

array([ 1. ,  5.5, 10. ])

In [219]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [220]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random을 사용하기 위한 numpy


랜덤값은 초기화를 하기 위해 사용합니다

In [221]:
# 0 에서 1 사이의 랜덤값
np.random.rand(4, 5, 3)

array([[[0.31435598, 0.50857069, 0.90756647],
        [0.24929223, 0.41038292, 0.75555114],
        [0.22879817, 0.07697991, 0.28975145],
        [0.16122129, 0.92969765, 0.80812038],
        [0.63340376, 0.87146059, 0.80367208]],

       [[0.18657006, 0.892559  , 0.53934224],
        [0.80744016, 0.8960913 , 0.31800347],
        [0.11005192, 0.22793516, 0.42710779],
        [0.81801477, 0.86073058, 0.00695213],
        [0.5107473 , 0.417411  , 0.22210781]],

       [[0.11986537, 0.33761517, 0.9429097 ],
        [0.32320293, 0.51879062, 0.70301896],
        [0.3636296 , 0.97178208, 0.96244729],
        [0.2517823 , 0.49724851, 0.30087831],
        [0.28484049, 0.03688695, 0.60956433]],

       [[0.50267902, 0.05147875, 0.27864646],
        [0.90826589, 0.23956189, 0.14489487],
        [0.48945276, 0.98565045, 0.24205527],
        [0.67213555, 0.76161962, 0.23763754],
        [0.72821635, 0.36778313, 0.63230583]]])

In [222]:
# 정규분포로 이루어진 랜덤값 생성하기
# 중요!

np.random.randn(10)

array([-0.29900735,  0.58685709,  2.19045563, -0.99053633, -0.56629773,
        0.09965137, -0.50347565, -1.55066343,  0.06856297, -1.06230371])

In [223]:
np.random.randn(3, 4, 2)

array([[[ 0.47359243, -0.91942423],
        [ 1.54993441, -0.78325329],
        [-0.32206152,  0.81351722],
        [-1.23086432,  0.22745993]],

       [[ 1.30714275, -1.60748323],
        [ 0.18463386,  0.25988279],
        [ 0.78182287, -1.23695071],
        [-1.32045661,  0.52194157]],

       [[ 0.29698467,  0.25049285],
        [ 0.34644821, -0.68002472],
        [ 0.2322537 ,  0.29307247],
        [-0.71435142,  1.86577451]]])

In [224]:
# 정수 랜덤 배열 만들기
np.random.randint(1, 100, size=(5,)) # size 는 형상을 의미

array([80, 61, 41, 33, 68])

In [225]:
np.random.randint(1, 100, size=(5,1)) # size 는 형상을 의미
# , 가 들어가면 2차원 배열로 출력

array([[33],
       [14],
       [21],
       [48],
       [20]])

In [226]:
np.random.randint(1, 100, size=(4,5,4))

array([[[ 8,  7, 67, 17],
        [33, 48, 76, 59],
        [86, 22, 30, 38],
        [51, 54,  8, 27],
        [27, 98, 21, 30]],

       [[97, 28, 64, 97],
        [69, 61, 48, 19],
        [ 4, 35, 64, 49],
        [17, 44, 92, 30],
        [93, 46,  6, 99]],

       [[37, 24, 93, 46],
        [53, 95, 99, 60],
        [97, 63, 85, 32],
        [87, 33, 67, 18],
        [25, 95, 54, 58]],

       [[67, 46, 24, 32],
        [47, 86, 23, 66],
        [27,  2, 90, 17],
        [33,  9, 43, 48],
        [39, 93, 42, 26]]])

In [227]:
# 랜덤 고정하기 seed 부여
np.random.seed(42)
np.random.randn(3,4)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [228]:
# 1차원 배열에서 랜덤 샘플링 하기 - choice
# 중요!

np.random.choice(100, size=(3,4)) # 0 ~ 99 까지의 숫자 중 랜덤하게 3 ,4 형식의 배열을 만들기

# 밑의 방법보다는 여기 방법을 더 자주 사용

array([[75, 57, 21, 88],
       [48, 90, 58, 41],
       [91, 59, 79, 14]])

In [229]:
arr = np.array([1, 2, 3, 4.5, 8.1, 9.0, 11])

np.random.choice(arr, size=(2,2), replace=False) # replace가 True면 중복 추출 허용, False 면 중복 추출 불허용

array([[1. , 2. ],
       [8.1, 4.5]])

In [230]:
# 확률 분포에 따른 ndarray 생성하기

# uniform : 균등분포
arr = np.random.uniform(1.0, 3.0, size=(4, 5)) # 1~3까지 4행 5열의 랜덤값을 생성한다.
arr

array([[2.18482914, 1.09290083, 2.2150897 , 1.34104825, 1.13010319],
       [2.89777107, 2.93126407, 2.6167947 , 1.60922754, 1.19534423],
       [2.36846605, 1.88030499, 1.24407647, 1.99035382, 1.06877704],
       [2.8186408 , 1.51755996, 2.32504457, 1.62342215, 2.04013604]])

In [231]:
# normal 또는 randn : 정규분포
# 좋은 기준을 위한 분포, 그래프

np.random.normal(size=(3,4))
np.random.randn(3,4)

array([[ 0.32408397, -0.38508228, -0.676922  ,  0.61167629],
       [ 1.03099952,  0.93128012, -0.83921752, -0.30921238],
       [ 0.33126343,  0.97554513, -0.47917424, -0.18565898]])

In [232]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
# 파이썬에서의 인덱스 자리를 해당 숫자로 바꾸는 방법

x[3] = 100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [234]:
# reshape 은 많이 중요함 제대로 기억해둘 것

x = x.reshape(2, 5)
x

array([[  0,   1,   2, 100,   4],
       [  5,   6,   7,   8,   9]])

In [235]:
# reshaep 결과값에 있는 100 을 다시 3으로 바꾸고 싶을때

x[0][3] = 3
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [236]:
# numpy 에서 가능한 방법

x[0,3]

3

In [237]:
# 전체 행

x[:, ]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [238]:
# 전체 행에서 인덱스가 2 인 것만 따로 빼내는 방법

x[:, 2]

array([2, 7])

In [239]:
# 0 에서 35까지의 수 를 3차원 배열로 표현
# 3차원 배열은 1개
# 2차원 배열은 3개
# 1차원 배열은 12개 
# 1차원이 담고있는 수는 3개(씩)

# 3차원 배열이 담고 있는 2차원 배열이 3개, 2차원 배열이 담고있는 1차원 배열이 4개, 
# 1차원 배열이 담고있는 스칼라(0차원 배열)가 3개(씩) 
# 그래서 3, 4, 3

x = np.arange(36).reshape(3,4,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [240]:
x.ndim

3

In [241]:
# 3차원(인덱스로 선택 자체가 불가능) 
# 2차원 배열 전체에서 1차원 배열에 대한 0,1 번째를 선택하고, 1차원 배열의 전체를 가져오게 하겠다. 

x[:, :2, :]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [242]:
# (...) 해당 차원 이후의 모든 데이터를 가져올때 사용하는 것

x[:2, ...]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [243]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [244]:
# 2차원 배열

x.shape

(3, 4)

In [245]:
# 원래의 2차원에서 4차원으로 만든다.

x2 = x[np.newaxis, :, :, np.newaxis]
x2.shape

(1, 3, 4, 1)

In [246]:
x2

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [247]:
# 2차원까지는 행렬이지만 3차원부터는 행렬 개념이 들어가지 않는다.

x3 = x[np.newaxis, ... , np.newaxis]
x3.shape

(1, 3, 4, 1)

In [248]:
# 1 을 날려버리기

x4 = np.squeeze(x3)
x4.shape

(3, 4)

## 배열의 형상 바꾸기


*   ravel()
*   flatten()
*   reshape()



In [249]:
# ravel flatten 평탄화 작업 효과는 같음
# 다른점은 복사본을 만들어내는지 아닌지

x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [250]:
# 배열을 풀어내주는 효과
temp = np.ravel(x)
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [251]:
# temp 를 바꿨는데, x 도 같이 바뀜
# 참조
# 평탄화된 모습만 갖고 옴
# ravel 의 특징
# flatten 은 새로운 배열을 다시 만들어냄
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [252]:
y = np.arange(15).reshape(3, 5)   # reshape 를 했을때 데이터 안의 개수가 상 원본과 같아야 한다.
temp2 = y.flatten()
print(temp)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [253]:
# temp2 의 값을 바꾼다고 해도 y 와 temp2 의 값이 다르다

temp2[0] = 100

print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [254]:
# 개수가 안맞으면 진행 할 수 없음

t = x.reshape(1, 3, 5, 1)
t.shape

(1, 3, 5, 1)

In [255]:
x = np.arange(36).reshape(3,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [256]:
temp = x.reshape(3,4,3)
temp.shape

(3, 4, 3)

In [257]:
temp = x.reshape(3,4,-1) # -1 을 넣어주면 자기가 알아서 계산해줌
temp.shape

(3, 4, 3)

In [258]:
temp = x.reshape(3,-1,3) # -1 을 넣어주면 자기가 알아서 계산해줌
temp.shape

(3, 4, 3)

In [259]:
temp = x.reshape(-1,-1,3) # -1 을 넣어주면 자기가 알아서 계산해줌, 단 -1 은 한번만 들어갈 수 있음
temp.shape

ValueError: ignored

## 브로드캐스팅
Shape 이 다른 두 ndarray에 대한 연산을 진행 한다

In [ ]:
# Shape 같을 때의 연산
# 2개는 Shape 자체는 같다.

x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3, 5)

print(x)
print(y)

In [ ]:
x + y

In [ ]:
x * y

In [ ]:
x * 2  # 스칼라값을 곱하면 자동으로 곱해지는 스칼라값이 브로드 캐스팅 된다.

In [ ]:
# Shape 다를 때의 연산
# 브로드 캐스팅은 뒤에 있는 숫자만 맞다면 가능
# 브로드 캐스팅은 행이 1개만 있을때 가능

a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

In [ ]:
a + b

In [ ]:
a + d

In [ ]:
e = np.arange(6).reshape(2, 3)
e.shape

In [ ]:
a + e

In [ ]:
b + e

In [ ]:
# 전치행렬 만드는 방법

e

In [ ]:
# e 를 전치행렬로 바꿔보자

e.T